dist: trusty
sudo: required
language: java
jdk:
- openjdk8
addons:
  apt:
    packages:
    - rpm
    - expect
env:
  global:
  - LC_ALL=C
  - secure: D0z+NkRKjlPCFfktyOvUMchLt3IdEco3bhfl3mMdP1btD+gLlZ2cLG0fDcH+9k2j7wIP/KBb6QxaADUdQ7Pjj446i/GwtQ4rrV+y9IOUUDTPWhXquj8JCdnfjHwGEIeu2nourINV8MhrxEBYyFpurJXpumadJxOBtnzaz30N2c4zFJNYzjG8v0TKoJURZj7MKOTXjz7T6yKI4aJj4OUcHd29Dy+r0HVj1kD26+bkUwsoEF+sdtHQz2a3aktpLisgUTfsY4XukqH4a1pftqTsB01+s73LY3N3kxGXPJ5Z8aQ5rkL/gWS7dQ32C5prSdGxRL52YL/BN37bzCZNdOTFF1xOX5xCb2m20pHzcVtVUz9orXthz+s81mqYk+0KFQ7eTGsiNICRe7DT0JbUFKqV8LH5x5N7yc7LfA2x+JDRLG9fQWzh35O2t0Q7zF007wfrEzid/YovAeBdStFLZhXwRCTbhp3WuG7M3jZjvtMZO+VX6/jFtVT18TTidXeaDDFs5vbm2JAwEpL//ORciwbNLkvqSys+qCmfbVlAj+3DvSOEGBBo3OPlPsGPozF86FlQmIPFivPRqb7GzreuSkQjF7jNcm5DczVH4raMn4pRmJajWp212Jl2NA0vxSwQi+35e/l0jDSMDGECgGCOeaY80lmrTBcaW3zeD2b+LqyiWg4=
  - secure: vd2qgVPmm6lWh56GyotOlU9DscXQ5jx2lHtaaUaixb1I3bhO2Ca9JXSE/k6XH2jIUjauKsFGUu9/X8IjM4s+h4blBeP+myjoDKl1daZYQEOn7qaa6UZpXo27zKhrJsGUp0yL3E8bQ7URjqP+xXpTbJf2AMMKjC3PZS8g0ddoVNMX6w1GV6PqnKntvy3BD+Cc/BN5Wk4SJOmit/cUrPm8jeCLJpfVb13tSlvdh/NdDyX3bDmB30JX2H3yKDU5aU+LkenBXo+ByYrKg+8+4TGiCL8C/IPtXB/RRe8u0BYjYSOOWbZFKQhVZaKTceJkxjU1wJXggkXyE5Coo5eaqPcyPgPb5FCTeqD+rSCi00/4rNShi/J9R4X4DQRrbRBXsmEZnge1NpZAOxB0Q9CT2wI3yVGif3maqTIUz8HYUB/RBzvz6l7R5NvDsMMFOAVZWF9f8XrIKTKkFOFG0AEDQM+QFSoovBvff3u79iv7I/l/ovAUIU7iz7zFJe4NjbdXz2/FktWvr9Dra4sV69CAXe/oTSNE4tn45zB/OLDqhEIldygZqt+HaJS1yfkoNrzfj3L1euZ5Z05iZZ7TgVJfzGePZIwgdfDCVaJNwTVDX5hvVn8NC98ltDYNCbVoj5B5pg+xVrqdam5bFTJwKl0F8HMy1hy39XzP3qHnaPEVNlpx+kI=
  - secure: qmDKB7cPJ8BOmVwhv8yhpYEcC/YYw8AKwROJMG5HorLdnPXeBWdf0QUeSwU7+m4pp1Px2hC0ccy2tFUAfodRJ3YjA6dHyydTm75RYkLkA4DYCg71IQ7hLmIa974dCg1283GGGJbEoKaZoVCJfD4gcaqTPvsm+/tCjzbWdzmKDoJZsKLnMuOqE/RvQJTNdaT28udf+JQP8zH3IQrRbI1N1NXWHziI8oKTf2pnZfNeetK+VHvx89tfOTP/TPI9vHu0GbRfoa9PsZGUFi7cTdZtWfS92u0cGq1Wyq01yausYLnq4oMfNvRhCIe8NYF7754izFBzAYQD9Xe+hGsfOdkaOH/SMhsqdSrqbPRLMZC18nkrM2yF+UdFXs6TGib4YoDXuaujns38KJO4ZyjDDFZeijuumlN1JduCpyTSM5ywqDfSw358QqKfrNCafLWhPLqKgL0GE34vGL+cOBPo8V9sEHfkLw1rbOMHzuMVI1fIHby5RQZDdDC0sli7VXqiKvLrV02OblTZRJqTY+sVuzV3mkPHiUhdRH4ePEQlf9PsGY2QF4MZEsR+G01An9K+rE1eQFWq75kLj3EAtdk1jPOQ4JNjd+KFEaC2BqJkYzUzO8V5oGOurQGSaDJiaKk45M0+XqEZlDcNfHpdYN49NsVVDvWdOyKxF6v8JgAYgqaUeUU=
install:
- git clone --branch 3.3 --depth=1 --no-single-branch https://github.com/Graylog2/graylog2-server ../graylog2-server
- (cd ../graylog2-server && mvn -DskipTests=true compile -B -V)
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.web.build=true -Dsource.skip=true -Dgpg.skip -B -V
script:
- mvn package -Dmaven.javadoc.skip=true -Dsource.skip=true -Dgpg.skip -B
after_success:
- openssl aes-256-cbc -K $encrypted_d573563e3aa2_key -iv $encrypted_d573563e3aa2_iv -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d
- gpg2 --import deployment/signingkey.asc
- gpg2 --allow-secret-key-import --import deployment/signingkey.asc
before_deploy:
- mvn jdeb:jdeb --settings deployment/settings.xml && export RELEASE_DEB_FILE=$(ls target/*.deb)
- mvn rpm:rpm --settings deployment/settings.xml && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
- rm -f target/original-*.jar
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: L0SCYpBQTuuXmzrl68iF8y80jjXRXtjQzdq+gbf0+hPGZuRxcl/UwJcEz4pOBNAmLy+zh+xz/IZPNNm/KnYLNrrJk69a1LsJ58H3xpis8ycdzjIQvXuJn6i7Pffrd5nER9TpsiokERzBlT7hiEJaB36pvxQGUVSbhoCxciQ8x+9Dnh4Xx6HFtbzqJlB69hQMA5r4ojOoinbbaM4qBr7/ypAydwuRiYiXFPWinL2JJHTLeDb5XSNyDcHqLOY3l9hPQ/mCuz1ufgyjbXBhVAd8zxsksjvVR5O6XUlSUxM/TWfSmmTgRnU23jJuOV1bSZWlMBeK6WNw2y6lxzR2BsEDa1c+HOAg33FNo9laMW7OTumI3Xsdy3vtCaPnb1cHKQH6cXSvu2vRzVNST8edwQjTs/jT842/Eodo0X7WH9Jdn+dI/L4zCk8O4OEeTMBBapBdujqhuRB0eHIAZxy4arEGFwKx/v1UtL9UgzWT+T1hX+T3Zk1JsnCg1IU9L0/J5OWrMB6jyFeyx5kU4s2/b83DDisyNq2LC8waML7Z7giyj8PMr5QKEjhF5/Fe21eGjBJaHjnzQwHlaFBkhHGbrmzQvDsh3KX0pxQKIdy0frsT1pvoxRqz7zvnUTvpF+DqmbQldh9ALGpdbJONLgIqmclui+NgshEU4dKPhMsOg6+dpI0=
  file: 
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_DEB_FILE}"
  - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    repo: airbus-cyber/graylog-plugin-logging-alert
    jdk: openjdk8
    tags: true
after_deploy:
- echo "Deploying release to Maven Central"
- mvn clean deploy -DskipTests=true --settings deployment/settings.xml
