#!/usr/bin/python3

from argparse import ArgumentParser
from graylog import Graylog

parser = ArgumentParser()
parser.add_argument('command', choices=['start', 'stop'])

arguments = parser.parse_args()

graylog = Graylog()
if arguments.command == 'start':
    graylog.start()
if arguments.command == 'stop':
    graylog.stop()
